import assert from "node:assert/strict";
import { test } from "node:test";
import {
  createWeddingContentService,
  type WeddingContentCommit,
  type WeddingContentRepository,
  type WeddingDocument,
  type WeddingRevision,
} from "../src/lib/wedding-content-service.ts";
import {
  defaultWeddingPage,
  type WeddingPageData,
  weddingPageDataSchema,
} from "../src/lib/wedding-page.ts";

class MemoryWeddingContentRepository implements WeddingContentRepository {
  document: WeddingDocument | null = null;
  revisions: WeddingRevision[] = [];

  readDocument() {
    return Promise.resolve(this.document);
  }

  readPublished() {
    return Promise.resolve(this.document?.published ?? null);
  }

  commit(input: WeddingContentCommit) {
    const currentVersion = this.document?.version ?? 0;
    if (currentVersion !== input.expectedVersion) {
      return Promise.resolve(null);
    }

    this.document = input.document;
    this.revisions.unshift(input.revision);
    return Promise.resolve(input.document);
  }

  listRevisions() {
    return Promise.resolve([...this.revisions]);
  }

  readRevision(id: string) {
    return Promise.resolve(this.revisions.find((revision) => revision.id === id) ?? null);
  }
}

const actor = { id: "user-1" };

function service(repository: MemoryWeddingContentRepository) {
  let nextId = 0;
  let tick = 0;
  return createWeddingContentService(repository, {
    createId: () => `revision-${++nextId}`,
    now: () => new Date(Date.UTC(2026, 8, 29, 12, 0, tick++)),
  });
}

function reorderedPage(): WeddingPageData {
  const [hero, details, schedule, ...remaining] = defaultWeddingPage.content;
  if (hero === undefined || details === undefined || schedule === undefined) {
    throw new Error("Default wedding page is incomplete.");
  }

  return {
    ...defaultWeddingPage,
    content: [schedule, hero, details, ...remaining],
  };
}

test("accepts safe photo URLs and rejects scriptable or arbitrary content", () => {
  const photo = {
    type: "PhotoBlock",
    props: {
      id: "photo-1",
      url: "https://images.example.com/garden.jpg",
      alt: "A garden in bloom",
      caption: "Botanica in September",
      shape: "landscape",
      visible: true,
    },
  } as const;
  assert.equal(
    weddingPageDataSchema.safeParse({
      ...defaultWeddingPage,
      content: [...defaultWeddingPage.content, photo],
    }).success,
    true,
  );

  for (const url of [
    "javascript:alert(1)",
    "data:image/svg+xml,<svg onload=alert(1) />",
    "http://x.test/a.jpg",
  ]) {
    const result = weddingPageDataSchema.safeParse({
      ...defaultWeddingPage,
      content: [...defaultWeddingPage.content, { ...photo, props: { ...photo.props, url } }],
    });
    assert.equal(result.success, false, url);
  }

  const arbitraryHtml = weddingPageDataSchema.safeParse({
    ...defaultWeddingPage,
    content: [
      {
        ...photo,
        props: { ...photo.props, html: "<script>alert(1)</script>" },
      },
    ],
  });
  assert.equal(arbitraryHtml.success, false);
});

test("accepts the root identifier injected into actual Puck payloads", () => {
  const puckPayload = structuredClone(defaultWeddingPage);
  puckPayload.root.props.id = "root";

  const parsed = weddingPageDataSchema.parse(puckPayload);
  assert.equal(parsed.root.props.id, "root");
  assert.equal(
    weddingPageDataSchema.safeParse({
      ...puckPayload,
      root: { props: { ...puckPayload.root.props, id: "not-the-puck-root" } },
    }).success,
    false,
  );
});

test("normalizes only safe metadata generated by the Puck root editor", () => {
  const puckPayload = {
    ...structuredClone(defaultWeddingPage),
    root: { ...defaultWeddingPage.root, readOnly: {} },
    zones: {},
  };
  assert.deepEqual(weddingPageDataSchema.parse(puckPayload), defaultWeddingPage);

  assert.equal(
    weddingPageDataSchema.safeParse({ ...puckPayload, zones: { "root:unexpected": [] } }).success,
    false,
  );
  assert.equal(
    weddingPageDataSchema.safeParse({
      ...puckPayload,
      root: { ...puckPayload.root, readOnly: { arbitrary: true } },
    }).success,
    false,
  );
});

test("keeps drafts private until an explicit publish and preserves block order", async () => {
  const repository = new MemoryWeddingContentRepository();
  const content = service(repository);
  const reordered = reorderedPage();

  const saved = await content.saveDraft({ data: reordered, expectedVersion: 0, actor });
  assert.equal(saved.version, 1);
  assert.equal(await content.loadPublished(), null);
  assert.deepEqual(
    saved.draft.content.map((block) => block.props.id),
    reordered.content.map((block) => block.props.id),
  );

  const published = await content.publish({ data: reordered, expectedVersion: 1, actor });
  assert.equal(published.version, 2);
  assert.deepEqual(
    (await content.loadPublished())?.content.map((block) => block.props.id),
    reordered.content.map((block) => block.props.id),
  );
});

test("rejects stale writes instead of overwriting a newer draft", async () => {
  const repository = new MemoryWeddingContentRepository();
  const content = service(repository);
  await content.saveDraft({ data: defaultWeddingPage, expectedVersion: 0, actor });

  await assert.rejects(
    content.saveDraft({ data: reorderedPage(), expectedVersion: 0, actor }),
    /changed in another session/i,
  );
  assert.equal(repository.document?.version, 1);
});

test("restores a historical revision as a new draft without republishing it", async () => {
  const repository = new MemoryWeddingContentRepository();
  const content = service(repository);
  const first = await content.saveDraft({ data: defaultWeddingPage, expectedVersion: 0, actor });
  const reordered = reorderedPage();
  const published = await content.publish({ data: reordered, expectedVersion: 1, actor });
  const firstRevision = first.revisions[0];
  if (firstRevision === undefined) {
    throw new Error("Expected the saved revision.");
  }

  const restored = await content.restoreDraft({
    revisionId: firstRevision.id,
    expectedVersion: published.version,
    actor,
  });

  assert.equal(restored.version, 3);
  assert.deepEqual(restored.draft, defaultWeddingPage);
  assert.deepEqual(await content.loadPublished(), reordered);
  assert.equal(restored.revisions[0]?.action, "restore");
});
