/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUuidRouteImport } from './routes/tools/uuid'
import { Route as ToolsUnixTimeRouteImport } from './routes/tools/unix-time'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'
import { Route as ToolsRgbRouteImport } from './routes/tools/rgb'
import { Route as ToolsJwtRouteImport } from './routes/tools/jwt'
import { Route as ToolsIpRouteImport } from './routes/tools/ip'
import { Route as ToolsCronRouteImport } from './routes/tools/cron'
import { Route as ToolsJsonRouteImport } from './routes/tools/json'
import { Route as ToolsYamlRouteImport } from './routes/tools/yaml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidRoute = ToolsUuidRouteImport.update({
  id: '/tools/uuid',
  path: '/tools/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUnixTimeRoute = ToolsUnixTimeRouteImport.update({
  id: '/tools/unix-time',
  path: '/tools/unix-time',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRgbRoute = ToolsRgbRouteImport.update({
  id: '/tools/rgb',
  path: '/tools/rgb',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJwtRoute = ToolsJwtRouteImport.update({
  id: '/tools/jwt',
  path: '/tools/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIpRoute = ToolsIpRouteImport.update({
  id: '/tools/ip',
  path: '/tools/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronRoute = ToolsCronRouteImport.update({
  id: '/tools/cron',
  path: '/tools/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonRoute = ToolsJsonRouteImport.update({
  id: '/tools/json',
  path: '/tools/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsYamlRoute = ToolsYamlRouteImport.update({
  id: '/tools/yaml',
  path: '/tools/yaml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/unix-time': typeof ToolsUnixTimeRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/rgb': typeof ToolsRgbRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/ip': typeof ToolsIpRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/yaml': typeof ToolsYamlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/unix-time': typeof ToolsUnixTimeRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/rgb': typeof ToolsRgbRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/ip': typeof ToolsIpRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/yaml': typeof ToolsYamlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/unix-time': typeof ToolsUnixTimeRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/rgb': typeof ToolsRgbRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/ip': typeof ToolsIpRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/yaml': typeof ToolsYamlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/uuid'
    | '/tools/unix-time'
    | '/tools/base64'
    | '/tools/rgb'
    | '/tools/jwt'
    | '/tools/ip'
    | '/tools/cron'
    | '/tools/json'
    | '/tools/yaml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/uuid'
    | '/tools/unix-time'
    | '/tools/base64'
    | '/tools/rgb'
    | '/tools/jwt'
    | '/tools/ip'
    | '/tools/cron'
    | '/tools/json'
    | '/tools/yaml'
  id:
    | '__root__'
    | '/'
    | '/tools/uuid'
    | '/tools/unix-time'
    | '/tools/base64'
    | '/tools/rgb'
    | '/tools/jwt'
    | '/tools/ip'
    | '/tools/cron'
    | '/tools/json'
    | '/tools/yaml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsUuidRoute: typeof ToolsUuidRoute
  ToolsUnixTimeRoute: typeof ToolsUnixTimeRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsRgbRoute: typeof ToolsRgbRoute
  ToolsJwtRoute: typeof ToolsJwtRoute
  ToolsIpRoute: typeof ToolsIpRoute
  ToolsCronRoute: typeof ToolsCronRoute
  ToolsJsonRoute: typeof ToolsJsonRoute
  ToolsYamlRoute: typeof ToolsYamlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid': {
      id: '/tools/uuid'
      path: '/tools/uuid'
      fullPath: '/tools/uuid'
      preLoaderRoute: typeof ToolsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/unix-time': {
      id: '/tools/unix-time'
      path: '/tools/unix-time'
      fullPath: '/tools/unix-time'
      preLoaderRoute: typeof ToolsUnixTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rgb': {
      id: '/tools/rgb'
      path: '/tools/rgb'
      fullPath: '/tools/rgb'
      preLoaderRoute: typeof ToolsRgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jwt': {
      id: '/tools/jwt'
      path: '/tools/jwt'
      fullPath: '/tools/jwt'
      preLoaderRoute: typeof ToolsJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ip': {
      id: '/tools/ip'
      path: '/tools/ip'
      fullPath: '/tools/ip'
      preLoaderRoute: typeof ToolsIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron': {
      id: '/tools/cron'
      path: '/tools/cron'
      fullPath: '/tools/cron'
      preLoaderRoute: typeof ToolsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json': {
      id: '/tools/json'
      path: '/tools/json'
      fullPath: '/tools/json'
      preLoaderRoute: typeof ToolsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/yaml': {
      id: '/tools/yaml'
      path: '/tools/yaml'
      fullPath: '/tools/yaml'
      preLoaderRoute: typeof ToolsYamlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsUuidRoute: ToolsUuidRoute,
  ToolsUnixTimeRoute: ToolsUnixTimeRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsRgbRoute: ToolsRgbRoute,
  ToolsJwtRoute: ToolsJwtRoute,
  ToolsIpRoute: ToolsIpRoute,
  ToolsCronRoute: ToolsCronRoute,
  ToolsJsonRoute: ToolsJsonRoute,
  ToolsYamlRoute: ToolsYamlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
