import type { DiscoveryResponse, Draft, DraftKind, Matter } from "./model.ts";
import { draftLabels, formatDate, kindLabels, MAX_DRAFT_LENGTH } from "./model.ts";

function responseSection(
  response: DiscoveryResponse,
  index: number,
  includeInternalNotes: boolean,
): string {
  const source = `${kindLabels[response.kind]} No. ${response.number}`;
  const request = response.request
    ? `Request: ${response.request}\n\n`
    : "[Original request not provided — add and verify before use.]\n\n";
  const notes =
    includeInternalNotes && response.note
      ? `INTERNAL ATTORNEY NOTES — NOT FOR OUTBOUND CORRESPONDENCE: ${response.note}\n\n`
      : "";
  return `${index + 1}. ${source}${response.status === "pending" ? " [FINDING NOT YET REVIEWED]" : ""}\n\n${request}Response provided (source excerpt):\n“${response.response}”\n\nPotential concerns for discussion:\n${response.issues.map((issue) => `• ${issue.explanation}`).join("\n")}\n\nRequested clarification or supplementation:\n${response.issues.map((issue) => `• ${issue.remedy}`).join("\n")}\n\n${notes}`;
}

export function createDraft(
  matter: Matter,
  kind: DraftKind,
  responseIds: string[],
  now = new Date(),
): Draft {
  const responses = matter.responses.filter(
    (response) =>
      responseIds.includes(response.id) &&
      response.issues.length > 0 &&
      response.status !== "dismissed",
  );
  if (responses.length === 0) {
    throw new Error("Select at least one flagged, non-dismissed response to include in the draft.");
  }
  const sections = responses
    .map((response, index) => responseSection(response, index, kind === "motion"))
    .join("\n");
  const commonHeader = `DRAFT — FOR ATTORNEY REVIEW ONLY\n${matter.isDemo ? "SAMPLE MATTER — FICTIONAL CONTENT. Do not use in an actual case.\n" : ""}Generated by local, rules-based triage. Findings are not legal conclusions. Verify the source, factual context, governing law, deadlines, and all placeholders before use.\n\n${matter.title}\nCase No. ${matter.caseNumber || "[Case number]"}\n${matter.court || "[Court and jurisdiction]"}\n\n`;
  const responseBy = matter.responseBy
    ? `Please provide supplemental responses by ${formatDate(matter.responseBy)} (a requested response date entered by counsel, not a calculated court deadline), or contact us to discuss a reasonable schedule.`
    : "Please contact us to agree on a reasonable date for supplemental responses. [Counsel: set a requested response date after verifying applicable deadlines.]";
  const letter = `${commonHeader}${formatDate(now.toISOString())}\n\nVia [agreed service method]\n${matter.opposingCounsel || "[Opposing counsel's name and address]"}\n\nRe: Meet and confer regarding discovery responses from ${matter.respondingParty || "[Responding party]"}\n\nCounsel:\n\nWe write on behalf of ${matter.client || "[Client]"} to discuss the following discovery responses and seek clarification or supplementation where appropriate. We would like to resolve these issues cooperatively without court intervention. These observations should be considered in light of the complete responses, any accompanying production, and the applicable discovery rules.\n\n${sections}\n${responseBy}\n\nWe are available for a substantive discussion at a mutually convenient time. Please let us know your availability and position on each item. If an issue cannot be resolved, we will evaluate what relief, if any, is appropriate under the governing rules.\n\nSincerely,\n${matter.sender || "[Your name and firm]"}\n\n[Verify recipient, source quotations, scope of requested relief, service requirements, and dates before sending.]`;
  const motion = `${commonHeader}WORKING OUTLINE — MOTION TO COMPEL FURTHER RESPONSES\n\n1. NOTICE AND REQUESTED RELIEF\n[Identify the moving and responding parties, the exact discovery set and disputed request numbers, the relief sought, hearing information, and any applicable notice requirements. Confirm that a motion to compel further responses is the correct procedural vehicle.]\n\n2. FACTUAL AND PROCEDURAL BACKGROUND\n[Insert verified dates of discovery service, response service, any extensions, and the relevant production history. Attach authenticated discovery and response exhibits.]\n\n3. MEET-AND-CONFER RECORD\n[Describe only communications that actually occurred. Insert dates, participants, substantive positions, and unresolved issues. A generated letter is NOT proof that a meet-and-confer took place. Attach supporting correspondence and any required declaration.]\n\n4. REQUEST-BY-REQUEST ANALYSIS\nThe following are potential issues identified for attorney review, not established deficiencies. Address each request's relevance, proportionality, wording, the complete response, and any legitimate objections.\n\n${sections}\n5. GOVERNING LAW AND TIMELINESS\n[Research and insert controlling statutes, rules, and verified authorities for the jurisdiction. Address the applicable filing deadline, method of service, extensions, and any separate-statement, certification, or local-rule requirements. No authorities or court deadlines have been generated.]\n\n6. RELIEF AND ANY SANCTIONS REQUEST\n[Specify the proposed further responses or production. Evaluate sanctions only if supported by the governing law and verified facts. Insert support for any amounts sought; do not invent fees or hours.]\n\n7. SUPPORTING MATERIALS\n[Prepare any required separate statement, supporting declaration, discovery and response exhibits, meet-and-confer correspondence, proposed order, and proof of service.]\n\nATTORNEY CHECKLIST\n□ Verify source quotations and original requests.\n□ Confirm factual history; do not treat draft correspondence as sent.\n□ Research governing and local rules and controlling authorities.\n□ Independently calculate and calendar all court deadlines.\n□ Confirm the proper procedural vehicle and requested relief.\n□ Replace all placeholders and conduct final legal review.\n\nPrepared for review by ${matter.sender || "[Your name and firm]"}.`;
  const content = kind === "letter" ? letter : motion;
  if (content.length > MAX_DRAFT_LENGTH) {
    throw new Error("This draft is too large. Select fewer responses and create separate drafts.");
  }
  return {
    id: crypto.randomUUID(),
    kind,
    title: draftLabels[kind],
    content,
    updatedAt: now.toISOString(),
    responseIds: responses.map((response) => response.id),
  };
}
